# Generated by Django 2.2 on 2020-11-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=3)),
                ('completed', models.BooleanField(default=False)),
                ('remaining_time', models.CharField(default='60', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('test_time', models.CharField(default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Test')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Test'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Test'),
        ),
    ]
